FROM node:18-alpine

WORKDIR /app

COPY packages/web/package*.json ./
RUN npm install

COPY packages/web/ ./

RUN npm run build

FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]