version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: temp_mail
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    environment:
      - DB_URL=postgresql://user:password@postgres:5432/temp_mail
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - JWT_SECRET=dev-secret
      - API_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ../packages/api:/app
      - /app/node_modules

  smtp:
    build:
      context: ..
      dockerfile: infra/Dockerfile.smtp
    environment:
      - DB_URL=postgresql://user:password@postgres:5432/temp_mail
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - SMTP_BIND_PORT=25
      - SMTP_HOSTNAME=localhost
    ports:
      - "25:25"
    depends_on:
      - postgres
      - minio
    volumes:
      - ../packages/smtp:/app
      - /app/node_modules
    cap_add:
      - NET_BIND_SERVICE

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.worker
    environment:
      - DB_URL=postgresql://user:password@postgres:5432/temp_mail
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ../packages/worker:/app
      - /app/node_modules

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    ports:
      - "3001:80"
    volumes:
      - ../packages/web:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - web

volumes:
  postgres_data:
  redis_data:
  minio_data: